### login
GET http://localhost:8080/login?userEmail=yupanzhao2022@163.com&password=123456 HTTP/1.1

### sendCode
GET http://localhost:8080/sendCode?userEmail=yupanzhao2022@163.com HTTP/1.1

### register
POST http://localhost:8080/register?userEmail=yupanzhao2022@163.com&password=123456&code=246301 HTTP/1.1

### pay_tokenless
GET http://localhost:8080/pay HTTP/1.1

### pay
GET http://localhost:8080/pay HTTP/1.1
Authorization: Bearer l2wneNpKYBjK38N8B118PKpuw8K4CQqD

### solve
GET http://localhost:8080/klotskiSolve HTTP/1.1
Content-Type: application/json
Authorization: Bearer XHfNE2ZVP6m29UQCx17l8dafpbI4gzj1

{
    "Width": 6,
    "Height": 6,
    "Data": [
        [0, 0, 1, 2, 2, 2],
        [3, 0, 1, 4, 0, 5],
        [3, 6, 6, 4, 0, 5],
        [0, 7, 0, 4, 0, 8],
        [0, 7, 9, 9, 0, 8],
        [0, 0, 0, 0, 0, 0]
    ],
    "BlockNumber": 9,
    "Target": 6
}